name: nice-apartment
favicon: null
layout_spectrum: 0.307858943939209
typography_spectrum: 0.31898562028072774
title: Old Town Apartment for Rent
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8984799589961767
  lightness: 0.7950240434147418
  saturation: 0.5308702990878373
  rhythmicContrast: 0.7823314920533448
purpose: []
